### ISSUE TITLE
App tagline being cut off strangely

### ISSUE THREAD

**Issue by janiew** [kscout/kscout.io#61]
![Screenshot from 2019-07-18 11-41-19](https://user-images.githubusercontent.com/35556896/61471632-1158fb00-a951-11e9-9a95-7928a58ddd98.png)

Fix by either:
- [ ] cutting off tagline with elipsis
- [ ] making font smaller on longer taglines
- [ ] something better that I haven't thought of

**Comment by Noah-Huppert** [comment]
acceptance requirements:

- [ ] All of tagline should be visible on all app cards
- [ ] Padding around tagline should be consistent on all sides on all app cards
