### ISSUE TITLE
Make chat bot button circular and in bottom right

### ISSUE THREAD

**Issue by Noah-Huppert** [kscout/kscout.io#79]
Make the chat bot button a circular button with a chat icon.

Place this button in the bottom right.

Acceptance criteria:

- [ ] (1) Chat bot button is in bottom right
- [ ] (2) Clicking chat bot button opens chat dialogue

**Comment by janiew** [comment]
I want to wait until we get chat redesign to fix this. Marking as wontfix for right now.

**Comment by Noah-Huppert** [comment]
We will open new tickets for the new design when it comes in.
